# Config file for typos. For more information, see: https://github.com/crate-ci/typos
[files]
extend-exclude = ["*.d.ts", "*.json", "*.lock", "*.map", "crates/rust-client/src/store/web_store/js", "dist"]
