//! Well-known procedure roots.
//! This file was generated by build.rs.

/// Procedure root of the `AuthRpoFalcon512` authentication component.
pub const AUTH_RPO_FALCON_512: &str =
    "0x7f9e4a997e88c1f30b51d6f9834291b600e2609867b4e597f089ff5329c23ff9";
