name: Lint
permissions:
  contents: read
on:
  push:
    branches: [main, next]
  pull_request:
    types: [opened, repoened, synchronize]

jobs:
  unused_deps:
    name: check for unused dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: machete
        uses: bnjbvr/cargo-machete@main
        
  typos:
    name: spellcheck
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        with:
          tool: typos
      - run: make typos-check

  toml:
    name: toml formatting
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        with:
          tool: taplo-cli
      - run: make toml-check
      
  eslint:
    name: "Typescript eslint checks"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make rust-client-ts-lint

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Install Rust with clippy
        run: |
          rustup update --no-self-update 
          rustup component add clippy
      - name: Add Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: make - clippy
        run: make clippy

  clippy-wasm:
    name: Clippy WASM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Install Rust with clippy
        run: |
          rustup update --no-self-update 
          rustup target add wasm32-unknown-unknown
          rustup component add clippy
      - name: Add Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: make - clippy-wasm
        run: make clippy-wasm

  format:
    name: format check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Install Rust with rustfmt
        run: |
          rustup update --no-self-update nightly
          rustup +nightly component add rustfmt
      - name: Add Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Install prettier
        run: yarn install
      - name: make - format-check
        run: make format-check

  rustdocs:
    name: build rust documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Install Rust
        run: rustup update --no-self-update
      - name: Add Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: make - doc
        run: make doc
