name: Web Client Docs

on:
  push:
    branches: [main, next]
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]


jobs:
  docs-check:
    name: Check that web client documentation is up-to-date
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Check for bypass label
        if: github.event_name == 'pull_request'
        id: bypass
        uses: actions/github-script@v6
        with:
          script: |
            const labels = context.payload.pull_request.labels.map(l => l.name);
            core.setOutput('skip', labels.includes('bypass-sdk-version-bump'));

      - name: Install Rust toolchain
        if: github.event_name == 'push' || steps.bypass.outputs.skip != 'true'
        run: rustup update --no-self-update

      - name: Setup Node.js
        if: github.event_name == 'push' || steps.bypass.outputs.skip != 'true'
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Add WASM target
        if: github.event_name == 'push' || steps.bypass.outputs.skip != 'true'
        run: rustup target add wasm32-unknown-unknown

      - name: Install Dependencies
        if: github.event_name == 'push' || steps.bypass.outputs.skip != 'true'
        working-directory: crates/web-client
        run: yarn install

      - name: Build Project
        if: github.event_name == 'push' || steps.bypass.outputs.skip != 'true'
        working-directory: crates/web-client
        run: yarn build

      - name: Generate Documentation
        if: github.event_name == 'push' || steps.bypass.outputs.skip != 'true'
        working-directory: crates/web-client
        run: yarn typedoc

      - name: Verify Documentation is Up-to-date
        if: github.event_name == 'push' || steps.bypass.outputs.skip != 'true'
        run: git diff --exit-code docs/src/web-client/api
